helm chart improvement 2

diff --git a/.github/workflows/add-verticadb-chart.yaml b/.github/workflows/add-verticadb-chart.yaml
--- a/.github/workflows/add-verticadb-chart.yaml
+++ b/.github/workflows/add-verticadb-chart.yaml
@@ -15,7 +15,7 @@ on:
         required: true
 
 env:
-  TARBALL_HOST: https://raw.githubusercontent.com/cchen-vertica/charts/main
+  TARBALL_HOST: https://raw.githubusercontent.com/cchen-vertica/charts/main/charts
   CHART_PREFIX: verticadb-operator
 
 jobs:
@@ -24,20 +24,22 @@ jobs:
     steps:
     - uses: actions/checkout@v3
 
-    - name: Download chart tarball
+    - name: Verify chart tarball exists
       run: |
-        curl \
-          --remote-name \
-          --show-error \
-          --location \
-          --fail \
-          ${TARBALL_HOST}/v${{ inputs.operator_version }}/$CHART_PREFIX-${{ inputs.operator_version }}.tgz
+        CHART_TARBALL=$CHART_PREFIX-${{ inputs.operator_version }}.tgz
+        if [ -f "charts/$CHART_TARBALL" ]; then
+          echo "Successfully found chart tarball: $CHART_TARBALL"
+        else
+          echo "Error: chart tarball $CHART_TARBALL not found."
+          exit 1
+        fi
 
     - name: Generate the helm repo index
       run: |
+        CHART_TARBALL=$CHART_PREFIX-${{ inputs.operator_version }}.tgz
         helm repo index \
           --merge index.yaml \
-          --url $TARBALL_HOST \
+          --url $TARBALL_HOST/$CHART_TARBALL \
           .
 
     - uses: stefanzweifel/git-auto-commit-action@v4
